class Empresa {/*class: modelador de objetos, mediante el cunstructor(function)*/
  constructor(e, n)
  {
    this.eCode = e;
    this.name = n;
  }
  options()
  {
    opciones.innerHTML += "<option value='" + this.eCode +"' id='" + this.eCode + "'>" + this.eCode + "</option>";
  }

    }
var Nempresa = document.getElementById("Nempresa")
var empresas = [];
empresas.push(new Empresa(2309,'CODIGO KAM'));
empresas.push(new Empresa(3169,'AUTOFLAME'));
empresas.push(new Empresa(3174,'PARQUE ARAUCO'));
empresas.push(new Empresa(3179,'TECNO BOGA'));
empresas.push(new Empresa(3209,'RKC SEGUROS'));
empresas.push(new Empresa(3210,'RKC SEGUROS'));
empresas.push(new Empresa(3249,'SHERATON'));
empresas.push(new Empresa(3266,'RKC SEGUROS'));
empresas.push(new Empresa(3268,'MONTEALTO'));
empresas.push(new Empresa(3302,'PACIFICO SUR'));
empresas.push(new Empresa(3330,'BANCO BICE'));
empresas.push(new Empresa(3336,'PAMELA OLIVARES'));
empresas.push(new Empresa(3339,'ACHS'));
empresas.push(new Empresa(3343,'COMPUTACION GRAFICA APLICADA Y CIA'));
empresas.push(new Empresa(3351,'PACIFICO SUR'));
empresas.push(new Empresa(3353,'SODEXO'));
empresas.push(new Empresa(3627,'ARMAS ARMAS'));
empresas.push(new Empresa(4663,'THB'));
empresas.push(new Empresa(4667,'HAGRAF'));
empresas.push(new Empresa(4725,'BICE VIDA'));
empresas.push(new Empresa(4727,'WILLIS'));
empresas.push(new Empresa(4756,'ALACERO'));
empresas.push(new Empresa(4785,'ICON CHILE'));
empresas.push(new Empresa(4847,'PRODUCCIO'));
empresas.push(new Empresa(4864,'ALIANZA SEGUROS'));
empresas.push(new Empresa(4887,'EDITORIAL DE LA A A LA Z'));
empresas.push(new Empresa(4896,'VERONICA FLECTHER'));
empresas.push(new Empresa(4906,'FOX VIDA'));
empresas.push(new Empresa(4912,'NEOSECURE'));
empresas.push(new Empresa(4929,'DRILLCO  TOOLS'));
empresas.push(new Empresa(4944,'CONVEOYR BELT'));
empresas.push(new Empresa(4954,'BRINKS CHILE'));
empresas.push(new Empresa(4968,'BRIDGESTONE'));
empresas.push(new Empresa(4974,'METLIFE'));
empresas.push(new Empresa(4977,'VULCO'));
empresas.push(new Empresa(5190,'ROYAL SANTIAGO HOTEL S.A.'));
empresas.push(new Empresa(5219,'CAS CHILE'));
empresas.push(new Empresa(5229,'BRAUN MEDICAL'));
empresas.push(new Empresa(5232,'CAE'));
empresas.push(new Empresa(5275,'HEWLETT PACKARD'));
empresas.push(new Empresa(5276,'ETECO'));
empresas.push(new Empresa(5277,'ISESA'));
empresas.push(new Empresa(5285,'GUANTE'));
empresas.push(new Empresa(5299,'DRILLCO  TOOLS'));
empresas.push(new Empresa(5304,'INNTEC'));
empresas.push(new Empresa(5305,'PARKER HANNIFIN'));
empresas.push(new Empresa(5308,'MONTEALTO'));
empresas.push(new Empresa(5311,'MONTEALTO'));
empresas.push(new Empresa(5313,'LA POLAR'));
empresas.push(new Empresa(5316,'PROTECMEDIA'));
empresas.push(new Empresa(5328,'FLSMIDTH'));
empresas.push(new Empresa(5329,'PIONEER'));
empresas.push(new Empresa(5332,'MULTIVAC CHILE'));
empresas.push(new Empresa(5342,'STEFANINI'));
empresas.push(new Empresa(5347,'INDUSTRIAL VIDA'));
empresas.push(new Empresa(5350,'STANTEC MWH'));
empresas.push(new Empresa(5351,'MUNCHENER'));
empresas.push(new Empresa(5357,'VALLE NEVADO'));
empresas.push(new Empresa(5360,'VIRUTEX'));
empresas.push(new Empresa(5361,'BRAUN MEDICAL'));
empresas.push(new Empresa(5362,'PRINAL'));
empresas.push(new Empresa(5363,'UNISYS'));
empresas.push(new Empresa(5364,'HOCHSHILD'));
empresas.push(new Empresa(5367,'MAVER'));
empresas.push(new Empresa(5371,'IBEROAMERICANA RADIO'));
empresas.push(new Empresa(5372,'CMPC'));
empresas.push(new Empresa(5373,'GRIFOLS CHILE'));
empresas.push(new Empresa(5374,'FERROSTAAL'));
empresas.push(new Empresa(5377,'IMP VIDA'));
empresas.push(new Empresa(5380,'CLOROX'));
empresas.push(new Empresa(5388,'TIAXA'));
empresas.push(new Empresa(5391,'TECNIGEN'));
empresas.push(new Empresa(5392,'TECHINT'));
empresas.push(new Empresa(5393,'INVERSIONES RECOLETA'));
empresas.push(new Empresa(5395,'PARQUE ARAUCO'));
empresas.push(new Empresa(5398,'PROMOTORA SORONDO'));
empresas.push(new Empresa(5399,'THB'));
empresas.push(new Empresa(5401,'QUIMICA CAMPO'));
empresas.push(new Empresa(5403,'CRUZ VERDE'));
empresas.push(new Empresa(5404,'LINDE GAS'));
empresas.push(new Empresa(5411,'ORION'));
empresas.push(new Empresa(5417,'PACIFICO SUR'));
empresas.push(new Empresa(5418,'PACIFICO SUR'));
empresas.push(new Empresa(5427,'DETROIT CHILE'));
empresas.push(new Empresa(5428,'BRISTOL MYERS'));
empresas.push(new Empresa(5440,'CAS CHILE'));
empresas.push(new Empresa(5442,'SARGENT'));
empresas.push(new Empresa(5443,'PACIFICO SUR'));
empresas.push(new Empresa(5451,'HAMBURG SUD CHILE'));
empresas.push(new Empresa(5467,'CAMARA ACHAM'));
empresas.push(new Empresa(5475,'PACIFICO SUR'));
empresas.push(new Empresa(5478,'AUTO SUMMIT'));
empresas.push(new Empresa(7015,'AMADEUS'));
empresas.push(new Empresa(8001,'SEMILLAS PIONEER'));
empresas.push(new Empresa(24627,'PHILIPS'));
empresas.push(new Empresa(69319,'I2B'));
empresas.push(new Empresa(69412,'SODEXO'));
empresas.push(new Empresa(69433,'AITEC'));
empresas.push(new Empresa(69509,'ECOCOPTER'));
empresas.push(new Empresa(69682,'PACIFICO SUR'));
empresas.push(new Empresa(69684,'DHL'));
empresas.push(new Empresa(69914,'CHEP CHILE'));
empresas.push(new Empresa(69929,'COLLOKY'));
empresas.push(new Empresa(70108,'TSOFT CHILE'));
empresas.push(new Empresa(70503,'SODEXO'));
empresas.push(new Empresa(70779,'THE BOSTON CONSULTING GROUP CHILE'));
empresas.push(new Empresa(70843,'PACE INTERNACIONAL'));
empresas.push(new Empresa(71109,'INFOR'));
empresas.push(new Empresa(71152,'VERONICA FLECTHER'));
empresas.push(new Empresa(71420,'TRAVEL INDUSTRY EXPERTS'));
empresas.push(new Empresa(71436,'PACIFICO SUR'));
empresas.push(new Empresa(71877,'ALTUM'));
empresas.push(new Empresa(72222,'VERONICA FLECTHER'));
empresas.push(new Empresa(72240,'LA ARAUCANA'));
empresas.push(new Empresa(72363,'GNL QUINTERO'));
empresas.push(new Empresa(72368,'SODEXO'));
empresas.push(new Empresa(72371,'ETECO'));
empresas.push(new Empresa(72536,'FRUTERA EUROAMERICA'));
empresas.push(new Empresa(72784,'CODIGO KAM'));
empresas.push(new Empresa(72954,'S+S SEGUROS'));
empresas.push(new Empresa(73225,'RKC SEGUROS'));
empresas.push(new Empresa(73817,'TRANSPORTES ILS'));
empresas.push(new Empresa(74075,'SODEXO'));
empresas.push(new Empresa(74335,'FILM HAUS'));
empresas.push(new Empresa(74777,'TRANSPORTES EXCLUSIVE'));
empresas.push(new Empresa(75159,'BIOTEQ WATER'));
empresas.push(new Empresa(75187,'ARTHUR GALLAGHER'));
empresas.push(new Empresa(75258,'SILFA'));
empresas.push(new Empresa(75324,'MIQ LOGISTICS'));
empresas.push(new Empresa(75342,'MOSAICO'));
empresas.push(new Empresa(75615,'RODRIGO ALBERTO GARCIA-HUIDOBRO TORO'));
empresas.push(new Empresa(75751,'SOLUCORP'));
empresas.push(new Empresa(75813,'PACIFICO SUR'));
empresas.push(new Empresa(76309,'QUIMATIC'));
empresas.push(new Empresa(76386,'CNBROKERS'));
empresas.push(new Empresa(76941,'PACIFICO SUR'));
empresas.push(new Empresa(77088,'THOROUGHTEC SIMULATION CHILE'));
empresas.push(new Empresa(86212,'GREAT PLACE TO WORK'));
empresas.push(new Empresa(86242,'PACIFICO SUR'));
empresas.push(new Empresa(86247,'SUMMIT AGRO'));
empresas.push(new Empresa(86250,'BANCHILE'));
empresas.push(new Empresa(86256,'PRODESA'));
empresas.push(new Empresa(86259,'MASTERFOODS'));
empresas.push(new Empresa(86260,'LIMAGRAIN'));
empresas.push(new Empresa(86319,'SEGUROS FERRECCIO'));
empresas.push(new Empresa(86327,'OPTIMISA'));
empresas.push(new Empresa(86331,'UPGRADE'));
empresas.push(new Empresa(86337,'PROA SEGUROS'));
empresas.push(new Empresa(86355,'BANINTER'));
empresas.push(new Empresa(86365,'CANON'));
empresas.push(new Empresa(86366,'AES GENER'));
empresas.push(new Empresa(86371,'LILIENFELD'));
empresas.push(new Empresa(86373,'PAULA GOMEZ VERA PRODUC.AUDIOVISUALES'));
empresas.push(new Empresa(86375,'BANINTER'));
empresas.push(new Empresa(86378,'MONTEALTO'));
empresas.push(new Empresa(86403,'THB'));
empresas.push(new Empresa(86408,'PACIFICO SUR'));
empresas.push(new Empresa(86410,'NEW TRADE BUNKAR'));
empresas.push(new Empresa(86414,'VIAL Y VIVES'));
empresas.push(new Empresa(86417,'UNIVERSIDAD RAUL SILVA'));
empresas.push(new Empresa(86419,'CLAUDIO ITURRA'));
empresas.push(new Empresa(86423,'ALQUIMIA CONCEPTOS'));
empresas.push(new Empresa(86432,'LOUSIANA PACIFIC'));
empresas.push(new Empresa(86433,'SEGUROS FERRECCIO'));
empresas.push(new Empresa(86434,'REVELLO'));
empresas.push(new Empresa(86438,'INNOPRINT'));
empresas.push(new Empresa(86442,'MOSAICO'));
empresas.push(new Empresa(86448,'LINDE GAS'));
empresas.push(new Empresa(86450,'VULCO'));
empresas.push(new Empresa(86468,'SEGUROS FERRECCIO'));
empresas.push(new Empresa(86474,'SSS CORREDORA'));
empresas.push(new Empresa(86513,'PRODUCE INSPECTORS OF AMERICA'));
empresas.push(new Empresa(86517,'360 PRODUCCIONES'));
empresas.push(new Empresa(86523,'LUIS IBARRA'));
empresas.push(new Empresa(86537,'KAINDL FLOORING'));
empresas.push(new Empresa(86550,'SERGIO RUIZ-TAGLE HUMERES'));
empresas.push(new Empresa(86554,'AGRICOLA NACIONAL'));
empresas.push(new Empresa(86559,'CONSULTORA Y CORREDORES DE SEGUROS LA CONCEPCION SPA'));
empresas.push(new Empresa(86607,'SEGUROS FERRECCIO'));
empresas.push(new Empresa(86612,'RKC SEGUROS'));
empresas.push(new Empresa(86619,'COLMENA'));
empresas.push(new Empresa(86620,'CORSEG'));
empresas.push(new Empresa(86639,"UNIVERSIDAD BERNARDO O'HIGGINS"));
empresas.push(new Empresa(86643,'MARCELO ANDRES HENOT DIAS'));
empresas.push(new Empresa(86664,'CANAL 13'));
empresas.push(new Empresa(86666,'KRONES'));
empresas.push(new Empresa(86670,'MONTENBAIK'));
empresas.push(new Empresa(86672,'BICE VIDA'));
empresas.push(new Empresa(86678,'WSN'));
empresas.push(new Empresa(86680,'SUMMIT AGRO'));
empresas.push(new Empresa(86687,'AON RISK'));
empresas.push(new Empresa(86691,'WILLIS'));
empresas.push(new Empresa(86692,'NEXO VIDA'));
empresas.push(new Empresa(86693,'LA CAMARA'));
empresas.push(new Empresa(86701,'VIGFOR'));
empresas.push(new Empresa(86706,'CAROLINA MANQUILEF'));
empresas.push(new Empresa(86713,'ALLIANCES S P A'));
empresas.push(new Empresa(86715,'SOC GESTORA COLEGIO PUERTO VARAS LIMIT'));
empresas.push(new Empresa(86728,'URETA Y FERNANDEZ'));
empresas.push(new Empresa(86730,'URETA Y FERNANDEZ'));
empresas.push(new Empresa(86735,'FEDERACION CHILENA DE HOCKEY SOBRE CESPED'));
empresas.push(new Empresa(86748,'CONO SUR'));
empresas.push(new Empresa(86756,'PENTAURUS'));
empresas.push(new Empresa(86758,'MERCER'));
empresas.push(new Empresa(86766,'CRODA'));
empresas.push(new Empresa(86777,'SKI PORTILLO'));
empresas.push(new Empresa(86780,'CODIGO KAM'));
empresas.push(new Empresa(86781,'OSCAR ANDRADE'));
empresas.push(new Empresa(86783,'RKC SEGUROS'));
empresas.push(new Empresa(86785,'ST COMPUTACION'));
empresas.push(new Empresa(86791,'MERCER'));
empresas.push(new Empresa(86798,'ERIEZ FLOTATION'));
empresas.push(new Empresa(86819,'TOP QUALITY'));
empresas.push(new Empresa(86824,'VIDRIOS DELLORTO'));
empresas.push(new Empresa(86825,'GENOA'));
empresas.push(new Empresa(86827,'CORPORACION DE DEPORTES DE LA CAMARA CHILENA DE LA CONSTRUCCION'));
empresas.push(new Empresa(86830,'FLEISCHMANN CHILE'));
empresas.push(new Empresa(86836,'FINCO BROKERS'));
empresas.push(new Empresa(86845,'PACIFICO SUR'));
empresas.push(new Empresa(86851,'GARNET'));
empresas.push(new Empresa(86856,'GARNET'));
empresas.push(new Empresa(86857,'PACIFICO SUR'));
empresas.push(new Empresa(86869,'BECTON DICKINSON'));
empresas.push(new Empresa(86870,'SCOTIABANK'));
empresas.push(new Empresa(86872,'CABIFY'));
empresas.push(new Empresa(86873,'MOK'));
empresas.push(new Empresa(86874,'UPGRADE'));
empresas.push(new Empresa(86902,'PACIFICO SUR'));
empresas.push(new Empresa(86903,'FUNDACION DAVIS'));
empresas.push(new Empresa(86911,'LILIENFELD'));
empresas.push(new Empresa(86920,'BANCO ESTADO'));
empresas.push(new Empresa(86923,'EMPRESAS CISANDINA'));
empresas.push(new Empresa(86924,'VALONTANO'));
empresas.push(new Empresa(86931,'ENJOY'));
empresas.push(new Empresa(86932,'MARIA SOLEDAD BARANDA'));
empresas.push(new Empresa(86937,'SURA'));
empresas.push(new Empresa(86942,'PRODUCER CORPORATIVO'));
empresas.push(new Empresa(86943,'GUANTE'));
empresas.push(new Empresa(86952,'MERCER'));
empresas.push(new Empresa(86953,'STARR INTERNATIONAL SEGUROS GENERALES S.A'));
empresas.push(new Empresa(86964,'VERONICA FLECTHER'));
empresas.push(new Empresa(86966,'SAE AGENCIA DE NEGOCIOS'));
empresas.push(new Empresa(86986,'RKC SEGUROS'));
empresas.push(new Empresa(86990,'JLT'));
empresas.push(new Empresa(86991,'INTELLIGENT MANAGEMENT'));
empresas.push(new Empresa(86995,'SCOTIABANK'));
empresas.push(new Empresa(86997,'TRANSUNION'));
empresas.push(new Empresa(87004,'PACIFICO SUR'));
empresas.push(new Empresa(87016,'UPGRADE'));
empresas.push(new Empresa(87023,'MERCER'));
empresas.push(new Empresa(87025,'RKC SEGUROS'));
empresas.push(new Empresa(87026,'UPGRADE'));
empresas.push(new Empresa(87027,'ACHS'));
empresas.push(new Empresa(87028,'RECUPERADORA DE METALES'));
empresas.push(new Empresa(87030,'PACIFICO SUR'));
empresas.push(new Empresa(87035,'LIBERTY'));
empresas.push(new Empresa(87045,'BCI CORREDORES'));
empresas.push(new Empresa(87047,'ZACH'));
empresas.push(new Empresa(87050,'LILIENFELD'));
empresas.push(new Empresa(87053,'INTEGRO CHILE'));
empresas.push(new Empresa(87054,'CONSALUD'));
empresas.push(new Empresa(87058,'UPGRADE'));
empresas.push(new Empresa(87061,'SEMILLAS PIONEER'));
empresas.push(new Empresa(87062,'SEMILLAS PIONEER'));
empresas.push(new Empresa(87069,'UPGRADE'));
empresas.push(new Empresa(87070,'UPGRADE'));
empresas.push(new Empresa(87076,'SCOTIABANK'));
empresas.push(new Empresa(87077,'SCOTIABANK'));
empresas.push(new Empresa(87084,'UPGRADE'));
empresas.push(new Empresa(87086,'CHEMIE'));
empresas.push(new Empresa(87090,'UPGRADE'));
empresas.push(new Empresa(87091,'AON RISK'));
empresas.push(new Empresa(87092,'ORIONT'));
empresas.push(new Empresa(87094,'ZURICH SANTANDER'));
empresas.push(new Empresa(87095,'ZURICH SANTANDER'));
empresas.push(new Empresa(87137,'ITALA'));
empresas.push(new Empresa(87141,'LILIENFELD'));
empresas.push(new Empresa(87145,'TEK CHILE'));
empresas.push(new Empresa(87146,'TENARIS'));
empresas.push(new Empresa(87164,'CONSORCIO'));
empresas.push(new Empresa(87165,'CONSALUD'));
empresas.push(new Empresa(87169,'BICE VIDA'));
empresas.push(new Empresa(87170,'PACIFICO SUR'));
empresas.push(new Empresa(87185,'PRESIDENCIA'));
empresas.push(new Empresa(87210,'UPGRADE'));
empresas.push(new Empresa(87215,'SKBERGE'));
empresas.push(new Empresa(87217,'SEGUROS AGESE'));
empresas.push(new Empresa(87220,'SCOTIABANK'));
empresas.push(new Empresa(87221,'SOPROLE'));
empresas.push(new Empresa(87222,'TECNO BOGA'));
empresas.push(new Empresa(87224,'AECI MINING'));
empresas.push(new Empresa(87234,'STARWOOD'));
empresas.push(new Empresa(87237,'MERCER'));
empresas.push(new Empresa(87239,'INVERSIONES SAN JOSE'));
empresas.push(new Empresa(87243,'PROA SEGUROS'));
empresas.push(new Empresa(87251,'PACIFICO SUR'));
empresas.push(new Empresa(87252,'MERCER'));
empresas.push(new Empresa(87261,'MATIAS IGNACIO LIZANA ALVARADO'));
empresas.push(new Empresa(87264,'SCOTIABANK'));
empresas.push(new Empresa(87268,'SPEAK UP'));
empresas.push(new Empresa(87274,'SMU'));
empresas.push(new Empresa(87281,'UNIDATA UNIDATA'));
empresas.push(new Empresa(87282,'MUNICIPALIDAD DE LAS CONDES'));
empresas.push(new Empresa(87284,'MERCER'));
empresas.push(new Empresa(87305,'GERMANISCHER LLOYD'));
empresas.push(new Empresa(87307,'VERONICA FLECTHER'));
empresas.push(new Empresa(87314,'SEGUROS CHILE'));
empresas.push(new Empresa(87315,'SCOTIABANK'));
empresas.push(new Empresa(87322,'GENOA'));
empresas.push(new Empresa(87331,'WOODTECH'));
empresas.push(new Empresa(87334,'BICE VIDA'));
empresas.push(new Empresa(87335,'HDI'));
empresas.push(new Empresa(87358,'THB'));
empresas.push(new Empresa(87361,'MUNICIPALIDAD LO BARNECHEA'));
empresas.push(new Empresa(87364,'SOUTHBRIDGE'));
empresas.push(new Empresa(87366,'VERONICA FLECTHER'));
empresas.push(new Empresa(87392,'MERCER'));
empresas.push(new Empresa(87398,'ENTEL'));
empresas.push(new Empresa(87413,'COLOMBINA COLOMBINA'));
empresas.push(new Empresa(87420,'ARTHUR GALLAGHER'));
empresas.push(new Empresa(87425,'OK CORREDORES'));
empresas.push(new Empresa(87432,'E SIGN'));
empresas.push(new Empresa(87434,'PROMET'));
empresas.push(new Empresa(87436,'CRUZ BLANCA'));
empresas.push(new Empresa(87445,'HDI'));
empresas.push(new Empresa(87460,'INTERGRAFICA'));
empresas.push(new Empresa(87464,'LLAVE MAESTRA'));
empresas.push(new Empresa(87467,'HDI'));
empresas.push(new Empresa(87475,'INVERSIONES RECOLETA'));
empresas.push(new Empresa(87479,'ENTEL ROAMING'));
empresas.push(new Empresa(87480,'UPGRADE'));
empresas.push(new Empresa(87484,'INTEREXPO'));
empresas.push(new Empresa(87490,'HOTEL W'));
empresas.push(new Empresa(87493,'AMPM CORREDORES DE SEGUROS'));
empresas.push(new Empresa(87509,'SIMPLEE'));
empresas.push(new Empresa(87511,'ALIANZA SEGUROS'));
empresas.push(new Empresa(87515,'BANCHILE'));
empresas.push(new Empresa(87517,'TRANSVIP'));
empresas.push(new Empresa(87520,'LILIENFELD'));
empresas.push(new Empresa(87525,'ZAVAL'));
empresas.push(new Empresa(87531,'EUROPCAR'));
empresas.push(new Empresa(87539,'BESALCO'));
empresas.push(new Empresa(87541,'SOUTHBRIDGE'));
empresas.push(new Empresa(87545,'SEGUROS FALABELLA'));
empresas.push(new Empresa(87549,'POLIGLOTA'));
empresas.push(new Empresa(87550,'HRD SEGUROS'));
empresas.push(new Empresa(87552,'AUTOMÓVIL CLUB'));
empresas.push(new Empresa(87562,'WILLIS TOWERS WATSON'));
empresas.push(new Empresa(87575,'CORREDORA DEL NORTE'));
empresas.push(new Empresa(87576,'DIANA SAEZ'));
empresas.push(new Empresa(87592,'AMPM CORREDORES DE SEGUROS'));
empresas.push(new Empresa(87593,'ROYAL SECURE'));
empresas.push(new Empresa(87599,'AUTOMÓVIL CLUB LANDING'));
empresas.push(new Empresa(87602,'U. DE CHILE FEMENINO'));
empresas.push(new Empresa(87606,'CUPONSTAR'));
empresas.push(new Empresa(87610,'FUERZA AEREA DE CHILE'));
empresas.push(new Empresa(87611,'SKY AIRLINE'));
empresas.push(new Empresa(87612,'TAAG GENETICS'));
empresas.push(new Empresa(87615,'CONVISION CONSULTORES CORPORATIVOS SPA'));
empresas.push(new Empresa(87619,'RIPLEY SEGUROS'));
empresas.push(new Empresa(87626,'TIGRE CHILE'));
empresas.push(new Empresa(87634,'INTERVIAL'));
empresas.push(new Empresa(87635,'SOUTHBRIDGE'));
empresas.push(new Empresa(87639,'AGUAS ANDINAS'));
empresas.push(new Empresa(87640,'TURNER CORREDORES'));
empresas.push(new Empresa(87644,'BEIERSDORF CHILE S.A.'));
empresas.push(new Empresa(87649,'ANDINA EMBOTELLADORA S.A.'));
empresas.push(new Empresa(87650,'Aerosan Airport Services'));
empresas.push(new Empresa(87651,'PROGRESO CORREDORES DE SEGUROS'));
empresas.push(new Empresa(87652,'PROGRESO CORREDORES DE SEGUROS LTDA'));
empresas.push(new Empresa(87653,'ALTA GASMAR S.A.'));
empresas.push(new Empresa(87654,'WILLIAMSON BALFOUR MOTORS SPA'));
empresas.push(new Empresa(87655,'POLIGAL SUD'));
empresas.push(new Empresa(87661,'PRDW ALDUNATE VASQUEZ INGENIEROS SPA.'));
empresas.push(new Empresa(87662,'CELLSTAR CHILE S.A.'));
empresas.push(new Empresa(87663,'CÁMARA DE COMERCIO DE SANTIAGO A.G.'));
empresas.push(new Empresa(87664,'AGRICOLA NACIONAL S.A.C E I.'));
empresas.push(new Empresa(87665,'ANASAC AMBIENTAL CHILE S.A.'));
empresas.push(new Empresa(87666,'ANASAC CHILE S.A.'));
empresas.push(new Empresa(87671,'EMPRESAS IANSA S.A.'));
empresas.push(new Empresa(87672,'AEROVÍAS DAP S.A.'));
empresas.push(new Empresa(87673,'CONTRALORÍA GENERAL DE LA REPUBLICA'));
empresas.push(new Empresa(87677,'SOCIEDAD AGRÍCOLA Y COMERCIAL LIMITADA'));
empresas.push(new Empresa(87678,'MERCER'));
empresas.push(new Empresa(87679,'MERCER'));
empresas.push(new Empresa(87682,'MERCER DIRECTO'));
empresas.push(new Empresa(87683,'INVERSIONES SAN JOSE'));
empresas.push(new Empresa(87684,'TIERRA AUSTRAL'));
empresas.push(new Empresa(87685,'SOC.SERV.TECNICOS GEOLOGICOS GEOTEC BOYLE BROS'));
empresas.push(new Empresa(87686,'MERCER'));
empresas.push(new Empresa(87687,'TECNOLOGIA  INTEGRAL S.A.'));
empresas.push(new Empresa(87690,'MERCER'));
empresas.push(new Empresa(87691,'IBER CORREDORES'));
empresas.push(new Empresa(87693,'MERCER'));
empresas.push(new Empresa(87697,'SEIDOR CHILE S.A.'));
empresas.push(new Empresa(87698,'PRESIDENCIA DE LA REPUBLICA'));
empresas.push(new Empresa(87699,'LUISA EMPERIALE'));
empresas.push(new Empresa(87703,'CAPS S.A.'));
empresas.push(new Empresa(87704,'TURISMO ANTARTICA XXI S.A.'));
empresas.push(new Empresa(87705,'SMURFIT KAPPA DE CHILE S.A'));
empresas.push(new Empresa(87709,'SCOTIABANK'));
empresas.push(new Empresa(87710,'AKVAGROUP CHILE S'));
empresas.push(new Empresa(87711,'OBSERVATORIO ASTRONÓMICO NACIONAL DE JAPON, NAOJ'));
empresas.push(new Empresa(87712,'KIA CHILE S.A.'));
empresas.push(new Empresa(87714,'BANCO BICE'));
empresas.push(new Empresa(87715,'CRAWFORD AFFINITY LTDA.'));
empresas.push(new Empresa(87716,'STARBUCKS COFEE CHILE S.A.'));
empresas.push(new Empresa(87717,'LIQUIDADORES DE SEGUROS EN RED CARVALLO LTDA'));
empresas.push(new Empresa(87718,'SOCIEDAD PUNTA DE LOBOS S.A.'));
empresas.push(new Empresa(87719,'DE VICENTE PLÁSTICOS S.A.'));
empresas.push(new Empresa(87720,'AGRICOLA ARIZTIA LTDA.'));
empresas.push(new Empresa(87721,'MERCER'));
empresas.push(new Empresa(87722,'AGRICOLA NACIONAL S.A.C E I. ( PLAN B)'));
empresas.push(new Empresa(87723,'CODEPACK S.A.'));
empresas.push(new Empresa(87725,'MCCANN ERICKSON S.A.DE PUBLICIDAD'));
empresas.push(new Empresa(87727,'TRANSPORTES ANDINOS S.A.'));
empresas.push(new Empresa(87728,'AMUNDI ASSET MANAGEMENT, AGENCIA EN CHILE'));
empresas.push(new Empresa(87730,'B. BOSCH S.A.'));
empresas.push(new Empresa(87732,'SOCIEDAD ELECTRICA DE MEDELLIN SPA'));
empresas.push(new Empresa(87733,'CONSTRUCTORA INARCO S.A.'));
empresas.push(new Empresa(87734,'GRAHAM MILLER LIQUIDADORES DE SEGUROS LTDA.'));
empresas.push(new Empresa(87735,'HOTELERA CHILE S.A.'));
empresas.push(new Empresa(87736,'CORREDORA DE SEGUROS COPELEC LTDA'));
empresas.push(new Empresa(87737,'ISDIN CHILE LIMITADA'));
empresas.push(new Empresa(87741,'DOREL JUVENILE CHILE S.A.'));
empresas.push(new Empresa(87742,'MERCER'));
empresas.push(new Empresa(87743,'MORALES BESA Y CIA LTDA'));
empresas.push(new Empresa(87744,'PETROQUIM S.A.'));
empresas.push(new Empresa(87747,'MERCER'));
empresas.push(new Empresa(87749,'VIU MANENT S.A.'));
empresas.push(new Empresa(87751,'MERCER'));
empresas.push(new Empresa(87752,'FUNDACIÓN TELETON'));
empresas.push(new Empresa(87754,'SOUTH PACIFIC LOGISTICS SPA'));
empresas.push(new Empresa(87756,'MERCER'));
empresas.push(new Empresa(87758,'BANCHILE CORREDORES DE BOLSA S.A.'));
empresas.push(new Empresa(87759,'ENTEL PCS TELECOMUNICACIONES S.A.'));
empresas.push(new Empresa(87760,'EMPRESA NACIONAL DE TELECOMUNICACIONES S.A.'));
empresas.push(new Empresa(87761,'ENTEL CALL CENTER S.A.'));
empresas.push(new Empresa(87762,'CARPENTER MARS FAC CHILE CORREDORES DE REASEGUROS LTDA.'));
empresas.push(new Empresa(87764,'OCEAN NETWORK EXPRESS (CHILE) SPA'));
empresas.push(new Empresa(87765,'COMPAÑÍA CHILENA DE COMUNICACIONES S.A.'));
empresas.push(new Empresa(87768,'WURTH CHILE LIMITADA'));
empresas.push(new Empresa(87770,'AGENCIAS BRINER CORREDORES DE SEGUROS S.A.'));
empresas.push(new Empresa(87771,'PRODUCTOS DEL MAR VENTISQUEROS S.A.'));
empresas.push(new Empresa(87773,'UNIVERSAL MCCANN SERVICIOS DE MEDIOS LTDA.'));
empresas.push(new Empresa(87776,'PONTIFICIA UNIVERSIDAD CATOLICA DE CHILE'));
empresas.push(new Empresa(87777,'CLASING DIRECTO'));
empresas.push(new Empresa(87782,'MERCER'));
empresas.push(new Empresa(87783,'SOCIEDAD MARÍTIMA Y COMERCIAL SOMARCO LTDA'));
empresas.push(new Empresa(87785,'CHILE FILMS SPA'));
empresas.push(new Empresa(87786,'FREELANCE CORPORATIVO'));
empresas.push(new Empresa(87786,'FREELANCE CORPORATIVO'));
empresas.push(new Empresa(87788,'CATAMUTUN ENERGÍA S.A.'));
empresas.push(new Empresa(87789,'MICROTEC S.A.'));
empresas.push(new Empresa(87790,'HORTIFRUT CHILE S.A.'));
empresas.push(new Empresa(87792,'SOUTHBRIDGE INTEGRACIÓN'));
empresas.push(new Empresa(87796,'VIÑA LOS BOLDOS LIMITADA'));
empresas.push(new Empresa(87797,'AKVA GROUP LAND BASED AMERICAS S.A.'));
empresas.push(new Empresa(87798,'SERVICIOS AEROPORTUARIOS AEROSAN S.A.'));
empresas.push(new Empresa(87800,'MASISA S.A.'));
empresas.push(new Empresa(87803,'CORREDORES ANS'));
empresas.push(new Empresa(87804,'MERCER'));
empresas.push(new Empresa(87807,'ENTEL WEB SERVICE'));
empresas.push(new Empresa(87808,'FR GROUP'));
empresas.push(new Empresa(87810,'BANCO DE CHILE'));
empresas.push(new Empresa(87815,'TELEVISIÓN NACIONAL DE CHILE'));
empresas.push(new Empresa(87818,'CIENTEC INSTRUMENTOS CIENTIFICOS S.A.'));
empresas.push(new Empresa(87819,'FIORDO AUSTRAL S.A.'));
empresas.push(new Empresa(87820,'SOUTH TRADE SHIPMANAGEMENT SPA'));
empresas.push(new Empresa(87823,'CPT WELLBOATS'));
empresas.push(new Empresa(87826,"L'OREAL CHILE S.A."));
empresas.push(new Empresa(87827,'NATURA COSMETICOS SA'));
empresas.push(new Empresa(87828,'BIT CORREDORES DE SEGUROS Y CRÉDITOS SPA'));
empresas.push(new Empresa(87831,'ZONA FRANCA DE IQUIQUE S.A.'));
empresas.push(new Empresa(87832,'HAPAG-LLOYD CHILE SPA '));
empresas.push(new Empresa(87833,'OXIQUIM S.A.'));
empresas.push(new Empresa(87834,'SCOTTA CHILE S.A.'));
empresas.push(new Empresa(87835,'EXPORTADORA BAIKA S.A.'));
empresas.push(new Empresa(87836,'BROTHER INTERNATIONAL DE CHILE'));
empresas.push(new Empresa(87837,'VIÑA UNDURRAGA S.A. '));
empresas.push(new Empresa(87838,'INDUSTRIAS CERESITA S.A. '));
empresas.push(new Empresa(87842,'ASOCIACIÓN DE EXPORTADORES DE FRUTAS DE CHILE A.G'));
empresas.push(new Empresa(87843,'EMPRESAS GASCO S.A.'));
empresas.push(new Empresa(87844,'DAVID DEL CURTO S.A.'));
empresas.push(new Empresa(87846,'INDUSTRIA DE ALIMENTOS DOS EN UNO S.A.'));
empresas.push(new Empresa(87847,'MARSOL S.A.'));
empresas.push(new Empresa(87848,'NEEDHAM  & ASOCIADOS'));
empresas.push(new Empresa(87849,'SEGURO SMART CORREDOR DE SEGUROS'));
empresas.push(new Empresa(87850,'COMERCIAL REINA SUR SPA'));
empresas.push(new Empresa(87851,'SOUTHBRIDGE CORPORATIVO'));
empresas.push(new Empresa(87852,'HOLDING DE SERVICIOS LATINOAMERICANOS S.A.'));
empresas.push(new Empresa(87861,'CORNERSHOP'));
empresas.push(new Empresa(87864,'AGRICOLA OCOA LTDA.'));
empresas.push(new Empresa(87868,'ACCOLADE WINE CHILE SPA'));
empresas.push(new Empresa(87869,'QUIMETAL INDUSTRIAL S A'));
empresas.push(new Empresa(87870,'ANDES CONNECTIONS S.A.'));
empresas.push(new Empresa(87871,'MERCER'));
empresas.push(new Empresa(87872,'CARLOS VERDUGO'));
empresas.push(new Empresa(87874,'MANTILLA CORREDORES DE SEGUROS'));
empresas.push(new Empresa(87876,'CORREDORES SANTA CRUZ'));
empresas.push(new Empresa(87877,'MERCER'));
empresas.push(new Empresa(87878,'COMPAÑÍA SUDAMERICANA DE VAPORES S.A.'));
empresas.push(new Empresa(87882,'INVERSIONES TORCA LIMITADA'));
empresas.push(new Empresa(87883,'RESITER S.A.'));
empresas.push(new Empresa(87885,'AGUAS ANDINAS'));
empresas.push(new Empresa(87887,'KIA CHILE S.A.'));
empresas.push(new Empresa(88178,'AEROLINEAS ARGENTINAS'));
empresas.push(new Empresa(99095,'AVIANCA'));

